version: '3.8'

services:
  yaml-json-service:
    build: .
    image: ${DOCKER_USERNAME:-leftyshields}/yaml-json-service:latest
    container_name: yaml-json-service
    ports:
      - "80:6001"
    environment:
      - NODE_ENV=production
      - PORT=6001
    volumes:
      # Mount uploads directory for persistence
      - uploads_data:/app/src/config/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:6001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  uploads_data:
