name: yaml-json-service
services:
- name: web
  source_dir: /
  github:
    repo: Leftyshields/yaml-json-service
    branch: main
    deploy_on_push: true
  run_command: node src/app.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
