#-------------------------------------------------------------------------------
# WBA Passpoint Profile Provisioning Certificate Attribute Definition
#-------------------------------------------------------------------------------
# This YAML file defines the structure and validation rules for the Wireless 
# Broadband Alliance (WBA) Passpoint Profile Provisioning certificate attribute.
# It specifies how to encode and validate certificate attributes used in 
# Passpoint (Hotspot 2.0) deployments for:
#
# - Organizational Identifier (OI) policies
# - FQDN (Fully Qualified Domain Name) policies  
# - SSID policies
# - Credential policies
#
# The attribute values use percent-encoded key-value pairs to enable secure and
# standardized provisioning of Passpoint profiles across different vendors and
# deployment scenarios.
#-------------------------------------------------------------------------------

server:
  host: localhost
  port: 6001

database:
  host: db.example.com
  port: 5432
  name: mydb

features:
  logging: true
  caching: false
  maxConnections: 100

# Note: standardized definitions will be updated to be inherited from 
# IETF RFCs, but are included in this draft to assist with ABNF checking

#-------------------------------------------------------------------------------
# OI Policy Description
#-------------------------------------------------------------------------------
# 1) value of home_ois key corresponds to one or more percent encoded, comma 
#    (",") delimited Organizational Identifiers (OIs) identifying the access 
#    networks that support authentication with this certificate. 
# 2) value of required_home_ois key corresponds to one or more percent encoded, 
#    comma (",") delimited OIs that are required to be advertised by an AP for the 
#    credential to be considered matching.
# 3) value of roaming_consortiums key corresponds to one or more percent 
#    encoded, comma (",") delimited OIs identifying the roaming consortiums of 
#    which the provider of the certificate credential is a member. The list is 
#    sorted from the most preferred one to the least preferred one.

#-------------------------------------------------------------------------------
# FQDN Policy Description
#-------------------------------------------------------------------------------
# 1) value of domain key corresponds to one or more percent encoded, comma 
#    (",") delimited FQDNs that are compared against the Domain Name List 
#    advertised by an AP used to indicate that the AP is operated by the Home SP.
# 2) value of domain_suffix_match key corresponds to the FQDN used as a suffix 
#    match against the AAA server certificate.
# 3) value of roaming_partner key encodes a concatenation of FQDN, MATCH 
#    PRIORITY and COUNTRYCODE, separated by percent encoded comma(",").

#-------------------------------------------------------------------------------
# SSID Policy Description
#-------------------------------------------------------------------------------
# 1) value of excluded_ssid key corresponds to one or more percent encoded, 
#    comma (",") delimited SSIDs that are used to exclude specific SSIDs from 
#    matching with the network. 

#-------------------------------------------------------------------------------
# Credential Policy Description
#-------------------------------------------------------------------------------
# 1) value of priority key corresponds to the priority of the certificate 
#    credential, i.e., PRIORITY. The higher the priority, the more preferred the 
#    credential.
# 2) value of ocsp key corresponds the OCSP stapling policy.
# 3) the value of realm key encodes the realm associated with the credential.
# 4) the value of username key encodes the username to be used with the 
#    credential.

passpoint:
  home_ois: "112233%2C445566"  # Note: using %2C as comma separator
  required_home_ois: "112233"
  roaming_consortiums: "112233,445566,778899"
  domain: "example.com,sub.example.com"
  domain_suffix_match: "*.example.com"
  roaming_partner: "roam.example.com%2C1%2C100%2CUS"
  excluded_ssid: "NoPasspoint%2CTestSSID"
  priority: "100"
  ocsp: "1"
  realm: "realm.example.com"
  username: "user.name"

schema:
  definitions:
    authority: 
      description: "ALPHA followed by ALPHA / DIGIT / hyphen / dot"
      pattern: "[A-Za-z][A-Za-z0-9\\-\\.]+"
    
    digit:
      description: "0-9"
      pattern: "[0-9]"
    
    nzdigit:
      description: "1-9"
      pattern: "[1-9]"
    
    u4digit:
      description: "0-4"
      pattern: "[0-4]"
    
    u5digit:
      description: "0-5"
      pattern: "[0-5]"
    
    alpha:
      description: "A-Z or a-z"
      pattern: "[A-Za-z]"
    
    upperhexdig:
      description: "Uppercase hex digit"
      pattern: "[0-9A-F]"
    
    lowerhexdig:
      description: "Lowercase hex digit"
      pattern: "[0-9a-f]"
    
    oi:
      description: "6-10 lowercase hex digits"
      pattern: "[0-9a-f]{6,10}"
    
    match:
      description: "0=exact match, 1=include subdomains"
      values: ["0", "1"]
    
    priority:
      description: "0-255"
      pattern: "([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])"
    
    countrycode:
      description: "Two alpha chars or %2A"
      pattern: "[A-Z]{2}|%2A"
    
    stapling:
      description: "OCSP stapling policy"
      values: 
        "0": "do not use OCSP stapling"
        "1": "try to use OCSP stapling"
        "2": "require valid OCSP stapling response"

    utf8_encoding:
      tail: "%x80-BF"
      utf8_2: "%xC2-DF UTF8-tail"
      utf8_3:
        - "%xE0 %xA0-BF UTF8-tail"
        - "%xE1-EC 2(UTF8-tail)"
        - "%xED %x80-9F UTF8-tail"
        - "%xEE-EF 2(UTF8-tail)"
      utf8_4:
        - "%xF0 %x90-BF 2(UTF8-tail)"
        - "%xF1-F3 3(UTF8-tail)"
        - "%xF4 %x80-8F 2(UTF8-tail)"